version: '3.8'
services:
  database:
    build:
      context: ./database
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://database:27017
    depends_on:
      - database
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  mongo_data: 