version: '3.8'
services:
  database:
    build:
      context: ./database
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://database:27017
      - OPENAI_API_KEY=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
    depends_on:
      - database
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  mongo_data: 